### ISSUE TITLE
As dev, I get all information of my flat files in a text config file

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/fusen#190]
## Validation

- [x] config file contains inflate params 
- [ ] It contains default values if not explicitly specified in the `inflate()` function

**To be refined**
- [ ] config yaml file contains:
  - [x] flat filename
  - [x] title of the vignette output if exists
  - [ ] Sections of the flat file (level 1, 2, 3 titles)
  - [ ] Names of functions under each section, and if there are exported or not
  - [ ] Names of R files created

## Tech

- [ ] Start by inflate parameters (issue #191).
- [ ] The rest will be more difficult to implement. Note that it is to be used in https://github.com/ThinkR-open/fusen/issues/189

```yaml
flat_clean_fusen_files.Rmd:
  path: dev/flat_clean_fusen_files.Rmd
  inflate:
    vignette_name: "Clean {fusen} files"
    check: FALSE
    overwrite: TRUE
    open_vignette: FALSE
  sections:
    section_level1: 
      title_level1: []
      section_level2: 
        title_level2: The details of each function linked to config:
        section_level3: 
          title_level3: "Keep it all, I am sure of the current state"
          functions: 
            register_all_to_config: export
          R_file: "clean_fusen_files.R"
          test_file: "test-clean_fusen_files.R"
        section_level3: 
          title_level3: "Protect existing R, tests and vignettes files"
          functions: 
            df_to_config: export
           files_list_to_vector: noRd
           update_one_group_yaml: noRd
          R_file: "clean_fusen_files.R"
          test_file: "test-clean_fusen_files.R"
  state: active
  R: R/clean_fusen_files.R
  tests: tests/testthat/test-clean_fusen_files.R
  vignettes: vignettes/clean-fusen-files.Rmd
```
