### ISSUE TITLE
Pass down flat vignette options to the inflated Rmd vignette

### ISSUE THREAD

**Issue by cpauvert** [ThinkR-open/fusen#197]
Hello,
First of all, thank you for the development of this package, this is really convenient!
However, I want to customize the vignettes that I am writing (e.g., TOC, numbered headings) but these options specified in the flat .Rmd vignette are not transferred to the inflated .Rmd.

 ```
---
title: "flat vignette title"
output: 
  html_document: 
    toc: yes
    number_sections: yes
editor_options: 
  chunk_output_type: console
---
 ```

Is this even possible, if so what is the recommended way? I could not find the information in the FAQ or the issues list.

BEst regards,
