### ISSUE TITLE
Last check for inflate_all()

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/fusen#206]
## Validation

- [x] There is no error with an old package that passed through register_all_to_config(), thus a section "keep" in the config file.
    - Tested on {fusen} itself
- [x] The configuration file does not mix `true` / `false` with `yes` / `no` => `true` / `false` would be better. 
    - `write_yaml_verbatim()` is now used when needed
![image](https://github.com/ThinkR-open/fusen/assets/21193866/796ca8e4-c90a-4b9a-9013-f0a18fef367d)

- [x] Allow to inflate all files, even if there are not named `flat_*.Rmd` => Merged in https://github.com/ThinkR-open/fusen/pull/213
![image](https://github.com/ThinkR-open/fusen/assets/21193866/ab52e2a0-7d09-4715-9abf-4a332a39114c)

- [x] Verify that inflated quarto qmd works
![image](https://github.com/ThinkR-open/fusen/assets/21193866/dc71b756-d3c9-4795-91b4-0411e8a78ac8)

- [x] Check problem with absolute path. Is it because there are `()` ? If yes, then ask the user to clean the directory name before. Maybe with clean_ascii_name() as a proposition?
![image](https://github.com/ThinkR-open/fusen/assets/21193866/dc523ef9-20fd-4709-931c-4b3e9ead6c34)

- [x] Verify that it works in VSCode too

![image](https://github.com/ThinkR-open/fusen/assets/21193866/363f5bbc-8d05-48e1-9a49-95231ba25fd1)

## Tech

- [x] Try to reproduce why sometimes there is still yes/no ? See `write_yaml_verbatim()`
    - [x] Maybe depends if run from `inflate()` or `inflate_all()` ?
- [x] Old version with only dev_history.Rmd does not work. It should also work with flats not named flat_*.Rmd
    + See https://github.com/statnmap/fusen.squirrels as a source example

![image](https://github.com/ThinkR-open/fusen/assets/21193866/31d17c31-e6bf-4126-b632-2157caac6ba2)

- [x] There should not be relative path here. Moreover `mnt/xx` is not a valid path

```yaml
dev_history.Rmd:
  path: mnt/Data/github/statnmap/fusen.squirrels (copie)/dev/dev_history.Rmd
  state: active
  R: /mnt/Data/github/statnmap/fusen.squirrels (copie)/R/check_data_integrity.R
  tests: /mnt/Data/github/statnmap/fusen.squirrels (copie)/tests/testthat/test-check_data_integrity.R
  vignettes: /mnt/Data/github/statnmap/fusen.squirrels (copie)/vignettes/get-started.Rmd
  inflate:
    flat_file: mnt/Data/github/statnmap/fusen.squirrels (copie)/dev/dev_history.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask

```
