### ISSUE TITLE
`inflate_all()` may not keep vignette name when different from entry name

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/fusen#231]
config_fusen.yaml only contains vignette name:

```yaml
dev_history_parse.Rmd:
  path: dev/dev_history_parse.Rmd
  state: active
  R: R/get_rmd_parts.R
  tests: tests/testthat/test-get_rmd_parts.R
  vignettes: vignettes/z-parse-a-rmd-or-qmd-file-into-a-tibble-and-vice-versa.Rmd
  inflate:
    flat_file: dev/dev_history_parse.Rmd
    vignette_name: z-Parse a Rmd or Qmd file into a tibble and vice-versa
    open_vignette: true
    check: false
    document: true
    overwrite: ask
```

although command was
```r
fusen::inflate(
  flat_file = file.path("dev", "dev_history_parse.Rmd"),
  vignette_name = c(
    "Parse a Rmd or Qmd file into a tibble and vice-versa" =
      "z-Parse a Rmd or Qmd file into a tibble and vice-versa"
  ),
  check = FALSE
)
```
